name: loan_simulator
description: "ローン計算アプリ"
publish_to: 'none'

version: 1.0.0+50

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  google_mobile_ads: ^5.1.0
  in_app_purchase: ^3.1.13
  csv: ^6.0.0
  share_plus: ^7.2.1
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
